### ISSUE TITLE
Compatibility with React 17

### ISSUE THREAD

**Issue by mobiware** [sendbird/chat-ai-widget#235]
Despite having React 17 listed as a supported peer dependency (see `package.json`), the Chat Ai Widget doesn't work in a React 17 app (we are getting a `useSyncExternalStore is not a function` error).

This seems to be due to the library depending on a recent version of `react-query` which only supports React 18

**Comment by bang9** [comment]
Hello, thank you for your report.
In the next version, we plan to improve by removing `react-query`.

Thank you.

**Comment by mobiware** [comment]
@bang9 thanks for your reply. Do you have any tentative schedule for this new version ?
Also, is there any workaround you can recommend in the meantime ?

**Comment by bang9** [comment]
It's under review #238

You do not necessarily need to use an npm module unless it is a special case.
We support widgets in the form of embed codes.
You can copy your code from the dashboard and paste it into your `index.html` or use something like `react-helmet`.

![image](https://github.com/sendbird/chat-ai-widget/assets/26326015/68244f41-ab27-489e-bc26-3daa40216bab)

**Comment by bang9** [comment]
[v1.5.10](https://github.com/sendbird/chat-ai-widget/releases/tag/v1.5.10) has been released
Would you like to try it with the new version?

**Comment by mobiware** [comment]
@bang9 yes, it works, thanks!
