### ISSUE TITLE
configureSession.onSessionTokenRequired is not triggered

### ISSUE THREAD

**Issue by mobiware** [sendbird/chat-ai-widget#266]
We are having issues getting `onSessionTokenRequired` to be called. We were able to replicate this issue using the real world example found in https://github.com/sendbird/chat-ai-widget-session-sample

The problem is that `onSessionTokenRequired` is only called if the `userId` was automatically created by the Sendbird chatbot.
This can be achieved by doing the following:
* in the sample app, remove or comment the `userId` and `configureSession` prop from the `ChatAiWidget` component
* run the sample app
* take note of the automatically assigned user id (this can be seen in the Network tab of the browser's Developer Tools). It uses the following format: `widget_<random 32 hexadecimal character string>`
* in the sample app, change the `USER_ID` variable to the previously obtained user id and uncomment the `userId` and `configureSession` props
* run the sample app again
* notice in the Console logs that `onSessionTokenRequired` is being called

Now if you change `USER_ID` to be any other user id and run the sample app, you won't see `onSessionTokenRequired` being called in the Console logs. We've tried the following cases:
* create a user using Sendbird's REST API and then set `USER_ID` to the newly created user's id in the sample app
* set `USER_ID` in the sample app to a brand new id that we have come up with. In this case a user with this id gets created in Sendbird, but we still don't see `onSessionTokenRequired`. being triggered.

Is this expected ?

**Comment by bang9** [comment]
Hello @mobiware, I apologize for the inconvenience.

I realized that I overlooked something while fixing the previously non-functional code.

How are you creating Sendbird users? To ensure that only users with a token can log in, you need to issue at least one session token or access token for the user.

When using the Chat SDK, it is designed to pass the authToken for connect by default, so the initial token issuance flow happens naturally. However, the existing interface of the Widget SDK was not set up this way. This is what I overlooked.

If you create the user in the following way, the issue should be resolved naturally.

### 1. create a user with `issue_access_token`
```ts
const createUser = async (userId: string) => {
  // todo: skip if user exists

  // create a user and issue access token
  const url = `https://api-${APP_ID}.sendbird.com/v3/users`;
  await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json; charset=utf8',
      'Api-Token': API_TOKEN,
    },
    body: JSON.stringify({ nickname: userId, user_id: userId, issue_access_token: true, profile_url:'' }),
  });
}
```

### 2. create a user and issue session token
```ts
const createUser = async (userId: string) => {
  // todo: skip if user exists

  // create a user
  const url = `https://api-${APP_ID}.sendbird.com/v3/users`;
  await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json; charset=utf8',
      'Api-Token': API_TOKEN,
    },
    body: JSON.stringify({ nickname: userId, user_id: userId, profile_url:'' }),
  });

  // issue session token
  await issueSessionToken(userId);
}

const App = () => {
  const [isLoading, setIsLoading] = useState(false);
  
  useEffect(() => {
    createUser('user_id').then(() => setIsLoading(false));
  }, []);
  
  if (isLoading) return null;
  return <ChatAiWidget {...} />
}
```

**Comment by bang9** [comment]
We will proceed with a patch to pass the initial authentication token using the same interface with Chat SDK.

**Comment by mobiware** [comment]
@bang9 thanks a lot for your advice, using option 1 did the trick and solved the issue.
Once you implement the patch you are mentioning in your message, will we still need to create the user prior to using the Chatbot ? Thanks !

**Comment by bang9** [comment]
@mobiware I'm glad to hear it's working well.
Yes, the token issuance API only works for users who have already been created.
