### ISSUE TITLE
Sendbird Chat AI Widget SDK upgrade breaks user authentication

### ISSUE THREAD

**Issue by mobiware** [sendbird/chat-ai-widget#313]
We've recently upgraded from `1.6.1` to `1.7.3` and user authentication is broken:
* `onSessionTokenRequired()` is no longer called when starting the chatbot
* the widget creates and uses a random user id like `widget_9e2e66d7e0a046378e12089387ad77e3` instead of using the user id provided by us

**Comment by bang9** [comment]
Hi @mobiware 

As mentioned in https://github.com/sendbird/chat-ai-widget/issues/266#issuecomment-2149935327, we have added a sessionToken prop for manual authentication in version [1.6.2](https://github.com/sendbird/chat-ai-widget/releases/tag/v1.6.2) to ensure proper functionality.

We've updated the guide with new information.
Could you please check it here?: https://github.com/sendbird/chat-ai-widget-session-sample/blob/main/src/App.tsx

I'm sorry for any confusion caused. 🙏

**Comment by mobiware** [comment]
@bang9 thanks for your reply, it works fine when following the latest instructions
